server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-dept
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  prefix: /eilen
  ignored-services: "*"
  routes:
    mydept.serviceId: microservice-dept
    mydept.path: /dept/**

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


